import pyspark.sql.types as st

schema = st.StructType(
    [
        st.StructField(name="player_name", dataType=st.StringType(), nullable=False),
        st.StructField(name="shirtnumber", dataType=st.StringType(), nullable=False),
        st.StructField(name="nationality", dataType=st.StringType(), nullable=False),
        st.StructField(name="position", dataType=st.StringType(), nullable=False),
        st.StructField(name="age", dataType=st.StringType(), nullable=False),
        st.StructField(name="minutes", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="goals", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="assists", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="penalties_made", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="penalties_attempted", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="shots", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="shots_on_target", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="cards_yellow", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="cards_red", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="touches", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="tackles", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="interceptions", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="blocks", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="dummy1", dataType=st.StringType(), nullable=True),
        st.StructField(name="dummy2", dataType=st.StringType(), nullable=True),
        st.StructField(name="dummy3", dataType=st.StringType(), nullable=True),
        st.StructField(name="dummy4", dataType=st.StringType(), nullable=True),
        st.StructField(name="dummy5", dataType=st.StringType(), nullable=True),
        st.StructField(name="passes_completed", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="passes", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="passes_pct", dataType=st.FloatType(), nullable=True),
        st.StructField(name="progressive_passes", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="carries", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="progressive_carries", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="take_ons", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="take_ons_won", dataType=st.IntegerType(), nullable=True),
        st.StructField(name="match_id", dataType=st.IntegerType(), nullable=False),
    ]
)
