from pyspark.sql.types import StructType, StructField, IntegerType, StringType

schema = StructType([
    StructField(name="player",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="age",
                dataType=IntegerType(),
                nullablebool=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_completed",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_pct",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_total_distance",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_progressive_distance",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_completed_short",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_short",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_pct_short",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_completed_medium",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_medium",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_pct_medium",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_completed_long",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_long",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_pct_long",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="assists",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="dummy1",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="dummy2",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="assisted_shots",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_into_final_third",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_into_penalty_area",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="crosses_into_penalty_area",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="progressive_passes",
                dataType=IntegerType(),
                nullablebool=True
                ),
])
