from pyspark.sql.types import StructType, StructField, IntegerType, StringType

schema = StructType([
    StructField(name="player_name",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullablebool=False
                ),
    StructField(name="age",
                dataType=IntegerType(),
                nullablebool=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="goals",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="assists",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="penalties_made",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="penalties_attempted",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="shots",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="shots_on_target",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="cards_yellow",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="cards_red",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="touches",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="tackles",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="interceptions",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="blocks",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="dummy1",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="dummy2",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="dummy3",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="dummy4",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="dummy5",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_completed",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="passes_pct",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="progressive_passes",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="carries",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="progressive_carries",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="take_ons",
                dataType=IntegerType(),
                nullablebool=True
                ),
    StructField(name="take_ons_won",
                dataType=IntegerType(),
                nullablebool=True
                ),
])

