version: "3"

services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ".env"
    volumes:
      - ./minio/data:/data
      - ./minio/buckets:/opt/minio
    restart: always
    networks:
      - backend

  prefect:
    build:
      context: .
      dockerfile: Dockerfile.prefect
    container_name: prefect
    volumes:
      - ./prefect/database:/root/.prefect
      - ./scraper/workflows:/opt/prefect/workflows
    env_file:
      - ".env"
    ports:
      - 4200:4200
    restart: always
    networks:
      - backend
    depends_on:
      - minio

  clickhouse:
    image: clickhouse/clickhouse-server:23.7.1.2470-alpine
    container_name: clickhouse
    user: "${UID}:${GID}"
    env_file:
      - ".env"
    ports:
      - 8123:8123
      - 9090:9000
    networks:
      - backend
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse/
      - ./clickhouse/logs:/var/log/clickhouse-server/

networks:
  backend: {}
