version: "3"

services:
  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ".env"
    volumes:
      - ./minio/data:/data
    restart: always
    networks:
      - backend

  prefect:
    build:
      context: .
      dockerfile: Dockerfile.prefect
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: prefect
    volumes:
      - ./prefect/database:/root/.prefect
      - ./scraper/workflows:/opt/prefect/workflows
    env_file:
      - ".env"
    ports:
      - 4200:4200
    restart: always
    networks:
      - backend
    depends_on:
      - minio

networks:
  backend: {}
