version: "3"

services:
  prefect:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: prefect
    networks:
      - backend
    restart: always
    volumes:
      - ./prefect/database:/root/.prefect
      - ./workflows:/opt/prefect/workflows
    env_file:
      - ".env"
    ports:
      - target: 4200
        published: 4200

  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z.fips
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    env_file:
      - ".env"
    volumes:
      - ./minio/data:/data
    networks:
      - backend

networks:
  backend: {}
