from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    FloatType
)

schema = StructType([
    StructField(name="player_name",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="age",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles_won",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles_defense_3rd",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles_mid_3rd",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles_attack_3rd",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="challenge_tackles",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="challenges",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="challenge_tackles_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="challenges_lost",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="blocks",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="blocked_shots",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="blocked_passes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="interceptions",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles_interceptions",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="clearances",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="errors",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="week",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="date",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_home",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_away",
                dataType=StringType(),
                nullable=False
                ),
])
