from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    FloatType
)

schema = StructType([
    StructField(name="player",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="age",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_shots_on_target_against",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_goals_against",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_saves",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_save_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="dummy1",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="gk_passes_completed_launched",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_passes_launched",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_passes_pct_launched",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="gk_passes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_passes_throws",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_pct_passes_launched",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="gk_passes_length_avg",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="gk_goal_kicks",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_pct_goal_kicks_launched",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="gk_goal_kick_length_avg",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="gk_crosses",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_crosses_stopped",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_crosses_stopped_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="gk_def_actions_outside_pen_area",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="gk_avg_distance_def_actions",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="week",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="date",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_home",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_away",
                dataType=StringType(),
                nullable=False
                ),
])
