from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    FloatType
)

schema = StructType([
    StructField(name="player_name",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="age",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="cards_yellow",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="cards_red",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="cards_yellow_red",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="fouls",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="fouled",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="offsides",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="crosses",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="interceptions",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles_won",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="pens_won",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="penalties_conceded",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="own_goals",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="ball_recoveries",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="aerials_won",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="aerials_lost",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="aerials_won_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="week",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="date",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_home",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_away",
                dataType=StringType(),
                nullable=False
                ),
])
