from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    FloatType
)

schema = StructType([
    StructField(name="player_name",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="age",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_completed",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="passes_total_distance",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_progressive_distance",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_completed_short",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_short",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_pct_short",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="passes_completed_medium",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_medium",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_pct_medium",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="passes_completed_long",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_long",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_pct_long",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="assists",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="dummy1",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="dummy2",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="assisted_shots",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_into_final_third",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_into_penalty_area",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="crosses_into_penalty_area",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="progressive_passes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="week",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="date",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_home",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_away",
                dataType=StringType(),
                nullable=False
                ),
])
