from pyspark.sql.types import StructType, StructField, IntegerType, StringType

schema = StructType([
    StructField(name="player_name",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="age",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_live",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_dead",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_free_kicks",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="through_balls",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_switches",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="crosses",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="throw_ins",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="corner_kicks",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="corner_kicks_in",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="corner_kicks_out",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="corner_kicks_straight",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_completed",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_offsides",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_blocked",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="week",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="date",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_home",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_away",
                dataType=StringType(),
                nullable=False
                ),
])
