from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    FloatType
)

schema = StructType([
    StructField(name="player_name",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="age",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches_defense_penalty_area",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches_defense_3rd",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches_mid_3rd",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches_attack_3rd",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches_attack_penalty_area",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches_live_ball",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="take_ons",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="take_ons_won",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="take_ons_won_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="take_ons_tackled",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="take_ons_tackled_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="carries",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="carries_distance",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="carries_progressive_distance",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="progressive_carries",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="carries_into_final_third",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="carries_into_penalty_area",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="miscontrols",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="dispossessed",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_received",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="progressive_passes_received",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="week",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="date",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_home",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_away",
                dataType=StringType(),
                nullable=False
                ),
])
