from pyspark.sql.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    FloatType
)

schema = StructType([
    StructField(name="player_name",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="shirtnumber",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="nationality",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="position",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="age",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="minutes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="goals",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="assists",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="penalties_made",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="penalties_attempted",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="shots",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="shots_on_target",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="cards_yellow",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="cards_red",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="touches",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="tackles",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="interceptions",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="blocks",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="dummy1",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="dummy2",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="dummy3",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="dummy4",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="dummy5",
                dataType=StringType(),
                nullable=True
                ),
    StructField(name="passes_completed",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="passes_pct",
                dataType=FloatType(),
                nullable=True
                ),
    StructField(name="progressive_passes",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="carries",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="progressive_carries",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="take_ons",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="take_ons_won",
                dataType=IntegerType(),
                nullable=True
                ),
    StructField(name="week",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="date",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_home",
                dataType=StringType(),
                nullable=False
                ),
    StructField(name="team_away",
                dataType=StringType(),
                nullable=False
                ),
])
