version: "3"

services:
  scrapper:
    build: .
    volumes:
      - .:/scrapper
  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z.fips
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    environment:
      - "MINIO_ROOT_USER=${MINIO_ROOT_USER}"
      - "MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}"
    volumes:
      - /minio/data:/data
